config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'welcome#index'

  devise_for :users, controllers: { invitations: 'users/invitations' }
  resources :users, only: %i[index show]

  resources :welcome, only: %i[index]

  resources :candidate_requests, except: %i[edit destroy]

  resources :polls, except: %i[edit update destroy] do
    get :fetch_result, on: :member
    resources :votes, only: %i[index new create]
  end
end

app/models/candidate_request.rb
# frozen_string_literal: true

class CandidateRequest < ApplicationRecord
  include ImageUploader::Attachment(:image)

  enum status: { pending: 0, approved: 1 }

  validate :check_image_size

  validates :voter_id, :status, presence: true
  validates :party, length: { maximum: 20 }
  validates :constituency, length: { maximum: 4 }

  def change_candidate_status
    @user = User.find(voter_id)
    @user.candidate!
    @user.save!

    new_candidate = Candidate.create(user_id: voter_id, party: party, constituency: constituency)
    new_candidate.save!
  end

  def check_image_size
    return if image.blank?

    errors.add(:image, 'Image size must not be greater then 1 mb') if image.size > 1.megabytes
  end
end

app/controllers/candidate_requests_controller.rb
# frozen_string_literal: true

# Candidate requests handled by admin
class CandidateRequestsController < ApplicationController
  before_action :set_candidate_request, only: %i[update]
  before_action :set_candidate_request_policy, only: %i[index new create]

  def index
    @requests = CandidateRequest.all
  end

  def new
    @request = CandidateRequest.new
  end

  def create
    @request = CandidateRequest.new(candidate_request_params)
    if @request.save
      flash[:notice] = t('candidate_request.create.req_approved')
      redirect_to :root
    else
      flash.now[:alert] = t('candidate_request.create.req_denied')
      render :new
    end
  end

  def update
    @request.approved!
    @request.change_candidate_status
    flash[:notice] = t('candidate_request.update.req_approved') if @request.save
    redirect_to :candidate_requests
  end

  private

  def candidate_request_params
    params.require(:candidate_request).permit(:party, :voter_id, :constituency, :image)
  end

  def set_candidate_request
    @request = CandidateRequest.find(params[:id])
    authorize @request
  end

  def set_candidate_request_policy
    authorize CandidateRequest
  end
end

app/helpers/candidate_requests_helper.rb
# frozen_string_literal: true

module CandidateRequestsHelper
  def requests(requests)
    render partial: 'candidate_requests/show_request', locals: { requests: requests }
  end
end

app/views/candidate_requests/_show_request.html.erb
<% requests.each do |request|%>
  <% if request.pending? %>
    <tr>
      <th scope="row"><%= request.id %></th>
      <td><%= request.voter_id %></td>
      <td><%= request.party %></td>
        <td><%= request.constituency %></td>

      <td>
          <%= button_to "Approve", candidate_request_path(request.id),method:'patch', params: { party: request.party, voter_id:request.voter_id, constituency:request.constituency}   %>
      </td>
    <tr>
  <% end%>
<% end %>

app/views/candidate_requests/index.html.erb
<p class="lead">
   Candidate Requests
</p>
<br>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Request Id</th>
      <th scope="col">Voter Id</th>
      <th scope="col">Party</th>
      <th scope="col">Constituency</th>
      <th scope="col">Request Status</th>
    </tr>
  </thead>

  <tbody>
      <%= requests(@requests) %>
  </tbody>

</table>

app/views/candidate_requests/new.html.erb
<section class="setter text-center">
<h2>Apply For Candidate Ship</h2>

<%= form_with model: @request, url: candidate_requests_path, local: true do |f| %>
  <%= render partial: "shared/validation_errors", locals: {obj: @request} %>

  <div class="field">
    <%= f.label :Party %><br />
    <%= f.text_field :party, autofocus: true, class:"form-control" , required:"true" %>
  </div>
  <br>

  <div class="field">
    <%= f.label :Symbol %><br />
    <%= f.file_field :image, class:"form-control", accept: 'image/png,image/jpeg,image/jpg,image/svg' , required:"true" %>
  </div>

  <div class=“field”>
      <%= f.hidden_field :voter_id, value: current_user.id %>
  </div>

  <div class=“field”>
      <%= f.hidden_field :constituency, value: current_user.constituency %>
  </div>

  <%= f.submit %>

<% end %>
</section>