config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'welcome#index'

  devise_for :users, controllers: { invitations: 'users/invitations' }
  resources :users, only: %i[index show]

  resources :welcome, only: %i[index]

  resources :candidate_requests, except: %i[edit destroy]

  resources :polls, except: %i[edit update destroy] do
    get :fetch_result, on: :member
    resources :votes, only: %i[index new create]
  end
end

app/models/poll.rb
# frozen_string_literal: true

class Poll < ApplicationRecord
  belongs_to :user
  has_many :votes, dependent: :destroy

  validates :start_date, presence: true
  validates :end_date, presence: true

  validate :end_date_is_after_start_date

  private

  def end_date_is_after_start_date
    return unless end_date.present? && start_date.present?

    errors.add(:end_date, 'cannot be before the start date') if end_date < start_date
  end
end

app/controllers/polls_controller.rb
# frozen_string_literal: true

# Manage Polls
class PollsController < ApplicationController
  before_action :set_poll, only: %i[show fetch_result]
  before_action :set_poll_policy, only: %i[index create new]

  def index
    @polls = Poll.all
  end

  def create
    @poll = current_user.polls.new(poll_params)
    if @poll.save
      flash[:notice] = t('poll.create.poll_created')
      redirect_to polls_path
    else
      render 'new'
    end
  end

  def new
    @poll = Poll.new
  end

  def show
    @candidates = Candidate.where(constituency: current_user.constituency)
  end

  def fetch_result
    @votes = @poll.votes
    @cons = ConstituencyResults.new(params).constituency_results
  end

  private

  def poll_params
    params.require(:poll).permit(:start_date, :end_date)
  end

  def set_poll
    @poll = Poll.find(params[:id])
    authorize @poll
  end

  def set_poll_policy
    authorize Poll
  end
end

app/helpers/polls_helper.rb
# frozen_string_literal: true

# Poll Helper
module PollsHelper
  def find_result(cons)
    unless cons.votes.empty?
      res = @votes.where(constituency_id: cons.id)
      res = res.group(:candidate_id).count(:id)
      winner = Candidate.find(res.keys[0])
      win_user = User.find(winner.user_id)
      candidate_request = CandidateRequest.find_by(voter_id: win_user.id)
      render partial: 'polls/show_result',
             locals: { cons: cons, res: res, winner: winner, win_user: win_user,
                       candidate_request: candidate_request }
    end
  end
end

app/views/polls/_cast_vote.html.erb
<% vote = current_user.votes.find_by(poll: @poll) %>
<% byebug %>
<% if vote.nil? %>
  <%= form_with( model: [ @poll, @poll.votes.build ], remote:true) do |form|  %>
    <% @candidates.each do |candidate| %>
      <%= form.radio_button :candidate_id, candidate.id%>
      <%= label :candidate_id, candidate.id %><br>
      <%= label :party, candidate.party %><br>
    <% end %>
    <%= form.hidden_field 'poll_id', value: @poll.id %>
    <%= form.hidden_field 'constituency_id', value: current_user.constituency %>

    <%= form.submit value="Cast Vote"%>
  <% end %>
<% else %>
  <div class="alert alert-primary" role="alert">
    <h4 class="lead"><b>You have already casted your vote.</b><h3>
  </div>
<% end %>

app/views/polls/_form.html.erb
<%= form_with(model: @poll, local: true) do |form| %>

  <div class="field lead text-center">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date %>
  </div>
  <br>

  <div class="field lead text-center">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date %>
  </div>
  <br>

  <div class="actions text-center">
    <%= form.submit %>
  </div>
<% end %>

app/views/polls/_poll_list.html.erb
<% polls.each do |poll| %>
  <tr>
    <td><%= poll.id %></td>
    <td><%= poll.start_date %></td>
    <td><%= poll.end_date %></td>


    <% if Time.now < poll.end_date %>
      <td><%= link_to "Cast Vote In Poll", poll_path(poll.id) %></td>
    <% else %>
      <td><%= "Poll Closed" %></td>
    <% end %>

    <% if Time.now > poll.end_date %>
      <td><%= link_to "Show Results", fetch_result_poll_path(poll.id) %></td>
    <% end %>
  </tr>
<% end %>

app/views/polls/_search_form.html.erb
<%= form_tag fetch_result_poll_path, method: 'get', class: "form-inline my-2 my-lg-0 ml-md-auto", id: "user-search" do %>
   <%= text_field_tag :term , params[:term], class: "form-control mr-sm-2 text-center common-btn", placeholder:"Search", autocomplete:"off" %>
   <div id="user-results"></div>
<% end %>

app/views/polls/_show_result.html.erb
<tr>
  <td> <%= cons.id %> </td>
  <td> <%= id = res.keys[0] %> </td>
  <td> <%= win_user.first_name %> </td>
  <td> <%= image_tag(candidate_request.image_url, style:'text-center', :size => "90x90", class: "rounded-circle") if candidate_request.image %> </td>
  <td> <%= res.values[0]%> </td>
</tr>

app/views/polls/fetch_result.html.erb
<p class="lead text-center">
   Constituency Results
</p>

<%= render partial: 'polls/search_form' %>

<br>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Constituency ID</th>
      <th scope="col">Winning Candidate ID</th>
      <th scope="col">Winner Name</th>
      <th scope="col">Symbol</th>
      <th scope="col">Vote Count</th>
    </tr>
  </thead>
  <tbody>
      <% @cons.each do |cons| %>
      <%= find_result(cons) %>
      <% end %>
  </tbody>
</table>


<%= paginate @cons, :class => 'pagination'%>

app/views/polls/index.html.erb
<p class="lead text-center">
   Poll's List
</p>
<br>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Poll ID</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Poll Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render partial: 'polls/poll_list', locals: {polls: @polls} %>
  </tbody>
</table>
<br>

app/views/polls/new.html.erb
<p class="lead text-center">Create New Poll</p>

<%= render 'form', poll: @poll %>

app/views/polls/show.html.erb
<p class="lead">
  <strong>Start date:</strong>
  <%= @poll.start_date %>
   <strong>&emsp; &emsp; End date:</strong>
  <%= @poll.end_date %>
</p>

<p class= "lead">
  <strong>Poll Status:</strong>
  <button type="button" class="btn btn-info">Active</button>
</p>

<% vote = current_user.votes.find_by(poll: @poll) %>
<% if vote.nil? %>
  <%= form_with( model: [ @poll, @poll.votes.build ], remote:true ) do |form|  %>
    <% @candidates.each do |candidate| %>
      <%= form.radio_button :candidate_id, candidate.id%>
      <%= label :candidate_id, candidate.id %><br>
      <%= label :party, candidate.party %><br>
    <% end %>
    <%= form.hidden_field 'poll_id', value: @poll.id %>
    <%= form.hidden_field 'constituency_id', value: current_user.constituency %>

    <%= form.submit value="Cast Vote"%>
  <% end %>
<% else %>
  <div class="alert alert-primary" role="alert">
    <h4 class="lead"><b>You have already casted your vote.</b><h3>
  </div>
<% end %>